// app-angular/src/app/components/preview/preview.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CandidateProfile } from '../../core/types';
import { assetUrl } from '../../core/utils/assets';

@Component({
  selector: 'app-preview',
  standalone: true,
  templateUrl: './preview.html',
})
export class Preview {
  @Input() data!: CandidateProfile;
  @Input() isLoading = false;
  @Input() isExisting = false;
  @Input() isFetching = false;
  @Output() add = new EventEmitter<void>();

  readonly logoUrl = assetUrl('icons/icon-32.png');

  get showSkeleton(): boolean {
    return this.isFetching || (!this.data?.firstName && !this.data?.lastName);
  }

  get initials(): string {
    return `${this.data?.firstName?.[0] ?? ''}${this.data?.lastName?.[0] ?? ''}`;
  }

  get avatarClass(): string {
    return `w-16 h-16 rounded-2xl overflow-hidden border border-[#e8ebf1] ${
      this.showSkeleton ? 'animate-shimmer bg-black/[0.04]' : 'bg-[#f5f7fa]'
    }`;
  }

  get statusBadgeClass(): string {
    const base = 'inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-sm font-medium tracking-[-0.02em]';
    return `${base} ${
      this.isExisting
        ? 'bg-[#ecfdf5] border border-[#a7f3d0] text-[#065f46]'
        : 'bg-[#fdf2f8] border border-[#fbcfe8] text-[#9d174d]'
    }`;
  }

  get ctaButtonClass(): string {
    const base =
      'w-full h-[40px] rounded-lg text-base font-semibold tracking-[-0.02em] transition-all duration-200 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed active:scale-[0.98]';
    return `${base} ${
      this.isExisting
        ? 'bg-white text-[#181c25] shadow-[0px_1px_2px_rgba(0,0,0,0.05),inset_0px_0px_0px_1px_#dde1e8] hover:bg-[#f5f7fa]'
        : 'bg-[#ff6a26] text-white shadow-[0px_1px_3px_rgba(255,106,38,0.2),0px_1px_2px_rgba(0,0,0,0.05)] hover:bg-[#e85814]'
    }`;
  }
}

// app/components/Preview.tsx
import React from 'react';
import { CandidateProfile } from '../types';

interface PreviewProps {
    data: CandidateProfile;
    onAdd: () => void;
    isLoading?: boolean;
    isExisting?: boolean;
    isFetching?: boolean;
}

// Info row component - light theme
const InfoRow: React.FC<{
    icon: React.ReactNode;
    label: string;
    value: string | React.ReactNode;
    isLink?: boolean;
    href?: string;
}> = ({ icon, label, value, isLink, href }) => (
    <div className="flex items-start gap-3 py-2.5 group">
        <div className="w-5 h-5 flex items-center justify-center text-[#687182] shrink-0 mt-0.5">
            {icon}
        </div>
        <div className="flex-1 min-w-0">
            <span className="text-sm font-medium tracking-[-0.01em] text-[#687182] uppercase block mb-1">
                {label}
            </span>
            {isLink ? (
                <a
                    href={href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-base font-medium tracking-[-0.02em] text-[#181c25] hover:text-[#2563eb] hover:underline underline-offset-2 block break-words"
                >
                    {value}
                </a>
            ) : typeof value === 'string' ? (
                <span className="text-base font-medium tracking-[-0.02em] text-[#181c25] block break-words leading-relaxed">
                    {value}
                </span>
            ) : (
                value
            )}
        </div>
    </div>
);

// Company tag - light theme
const CompanyTag: React.FC<{ name: string; logoUrl?: string }> = ({ name, logoUrl }) => (
    <div className="inline-flex items-center gap-1.5 px-2 py-1 rounded-md bg-[#eff6ff] border border-[#bfdbfe]">
        {logoUrl ? (
            <img src={logoUrl} alt="" className="w-4 h-4 rounded-sm object-cover" />
        ) : (
            <div className="w-4 h-4 rounded-sm bg-[#2563eb]/20 flex items-center justify-center">
                <svg className="w-2.5 h-2.5 text-[#1e40af]" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clipRule="evenodd" />
                </svg>
            </div>
        )}
        <span className="text-base font-medium tracking-[-0.02em] text-[#1e40af]">{name}</span>
    </div>
);

// Skeleton row for loading state
const SkeletonRow: React.FC = () => (
    <div className="flex items-center gap-3 py-2.5">
        <div className="w-5 h-5 rounded bg-black/[0.04] animate-shimmer shrink-0" />
        <div className="w-[90px] h-4 rounded bg-black/[0.04] animate-shimmer shrink-0" />
        <div className="flex-1 h-4 rounded bg-black/[0.04] animate-shimmer" />
    </div>
);

export const Preview: React.FC<PreviewProps> = ({
    data,
    onAdd,
    isLoading,
    isExisting,
    isFetching
}) => {
    const showSkeleton = isFetching || (!data.firstName && !data.lastName);

    return (
        <div className="fixed right-5 top-16 w-[420px] bg-white rounded-xl shadow-[0px_0px_0px_1px_#dde1e8,0px_4px_6px_-1px_rgba(0,0,0,0.1),0px_2px_4px_-2px_rgba(0,0,0,0.1)] overflow-hidden font-sans z-[2147483647] pointer-events-auto animate-fade-in-up">

            {/* Header with Yena branding */}
            <div className="flex items-center justify-between px-4 py-3 border-b border-[#e8ebf1]">
                <div className="flex items-center gap-2">
                    <div className="w-7 h-7 rounded-lg bg-[#ff6a26] flex items-center justify-center shadow-sm">
                        <img
                            src={chrome.runtime.getURL('icons/icon-32.png')}
                            alt="Yena"
                            className="w-4 h-4 object-contain"
                        />
                    </div>
                    <span className="text-base font-semibold tracking-[-0.02em] text-[#181c25]">Yena</span>
                </div>
            </div>

            {/* Status Badge */}
            <div className="flex justify-center py-4">
                {showSkeleton ? (
                    <div className="h-5 w-32 rounded-full bg-black/[0.04] animate-shimmer" />
                ) : (
                    <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-sm font-medium tracking-[-0.02em] ${isExisting
                        ? 'bg-[#ecfdf5] border border-[#a7f3d0] text-[#065f46]'
                        : 'bg-[#fdf2f8] border border-[#fbcfe8] text-[#9d174d]'
                        }`}>
                        {isExisting ? (
                            <>
                                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                                </svg>
                                In Yena
                            </>
                        ) : (
                            <>
                                <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                                </svg>
                                Record Suggestion
                            </>
                        )}
                    </div>
                )}
            </div>

            {/* Avatar */}
            <div className="flex justify-center pb-4">
                <div className={`w-16 h-16 rounded-2xl overflow-hidden border border-[#e8ebf1] ${showSkeleton ? 'animate-shimmer bg-black/[0.04]' : 'bg-[#f5f7fa]'}`}>
                    {!showSkeleton && (
                        data.profilePictureUrl ? (
                            <img src={data.profilePictureUrl} alt="" className="w-full h-full object-cover" />
                        ) : (
                            <div className="w-full h-full flex items-center justify-center">
                                <span className="text-2xl font-semibold text-[#181c25]">
                                    {data.firstName?.[0]}{data.lastName?.[0]}
                                </span>
                            </div>
                        )
                    )}
                </div>
            </div>

            {/* Name */}
            <div className="text-center px-4 pb-4">
                {showSkeleton ? (
                    <div className="flex flex-col items-center gap-2">
                        <div className="h-6 w-40 rounded bg-black/[0.04] animate-shimmer" />
                    </div>
                ) : (
                    <div className="flex items-center justify-center gap-2">
                        <h2 className="text-xl font-semibold tracking-[-0.02em] text-[#181c25]">
                            {data.firstName} {data.lastName}
                        </h2>
                        {data.connectionDegree && (
                            <span className="inline-flex items-center px-2 py-0.5 rounded-md bg-[#eff6ff] border border-[#bfdbfe] text-sm font-medium text-[#1e40af]">
                                {data.connectionDegree}
                            </span>
                        )}
                    </div>
                )}
            </div>

            {/* Separator */}
            <div className="h-px bg-[#e8ebf1] mx-4" />

            {/* Info Rows */}
            <div className="px-4 py-2">
                {showSkeleton ? (
                    <>
                        <SkeletonRow />
                        <SkeletonRow />
                        <SkeletonRow />
                        <SkeletonRow />
                        <SkeletonRow />
                    </>
                ) : (
                    <>
                        {data.headline && (
                            <InfoRow
                                icon={
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                    </svg>
                                }
                                label="Description"
                                value={data.headline}
                            />
                        )}
                        {data.location && (
                            <InfoRow
                                icon={
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                                    </svg>
                                }
                                label="Location"
                                value={data.location}
                            />
                        )}
                        {data.currentCompany && (
                            <InfoRow
                                icon={
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                                    </svg>
                                }
                                label="Company"
                                value={<CompanyTag name={data.currentCompany} />}
                            />
                        )}
                        {data.experiences?.[0]?.title && (
                            <InfoRow
                                icon={
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                                    </svg>
                                }
                                label="Job title"
                                value={data.experiences[0].title}
                            />
                        )}
                        <InfoRow
                            icon={
                                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                                    <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                                </svg>
                            }
                            label="LinkedIn"
                            value="View Profile"
                            isLink
                            href={data.linkedinUrl}
                        />
                    </>
                )}
            </div>

            {/* CTA Button */}
            <div className="px-4 pt-2 pb-2">
                <button
                    onClick={onAdd}
                    disabled={isLoading || showSkeleton}
                    className={`w-full h-[40px] rounded-lg text-base font-semibold tracking-[-0.02em] transition-all duration-200 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed active:scale-[0.98] ${isExisting
                        ? 'bg-white text-[#181c25] shadow-[0px_1px_2px_rgba(0,0,0,0.05),inset_0px_0px_0px_1px_#dde1e8] hover:bg-[#f5f7fa]'
                        : 'bg-[#ff6a26] text-white shadow-[0px_1px_3px_rgba(255,106,38,0.2),0px_1px_2px_rgba(0,0,0,0.05)] hover:bg-[#e85814]'
                        }`}
                >
                    {isLoading ? (
                        <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                        </svg>
                    ) : showSkeleton ? (
                        <>
                            <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                            </svg>
                            Loading...
                        </>
                    ) : isExisting ? (
                        <>
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                            </svg>
                            View in Yena
                        </>
                    ) : (
                        <>
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                            </svg>
                            Add Person to Yena
                        </>
                    )}
                </button>
            </div>

        </div>
    );
};
